//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hht.SampleInspection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleInspectionEntities : DbContext
    {
        public SampleInspectionEntities()
            : base("name=SampleInspectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditor> Auditors { get; set; }
        public virtual DbSet<InspectionType> InspectionTypes { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartCategory> PartCategories { get; set; }
        public virtual DbSet<PartReceived> PartReceiveds { get; set; }
        public virtual DbSet<Valve> Valves { get; set; }
        public virtual DbSet<ValveControlType> ValveControlTypes { get; set; }
        public virtual DbSet<ValveFuelType> ValveFuelTypes { get; set; }
        public virtual DbSet<ValveTestResult> ValveTestResults { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WhereFound> WhereFounds { get; set; }
        public virtual DbSet<PassFail03> PassFail03 { get; set; }
        public virtual DbSet<PassFail04> PassFail04 { get; set; }
        public virtual DbSet<PassFail08> PassFail08 { get; set; }
        public virtual DbSet<PassFail11> PassFail11 { get; set; }
        public virtual DbSet<PassFail13> PassFail13 { get; set; }
        public virtual DbSet<WasTested> WasTesteds { get; set; }
    }
}
