//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hht.SampleInspection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValveTestResult
    {
        public int PartReceivedId { get; set; }
        public short Step03TestResultId { get; set; }
        public Nullable<decimal> Step05mH { get; set; }
        public Nullable<decimal> Step06mH { get; set; }
        public short Step13TestResultId { get; set; }
        public Nullable<decimal> Step10High { get; set; }
        public Nullable<decimal> Step10Low { get; set; }
        public short Step11TestResultId { get; set; }
        public short Step08TestResultId { get; set; }
        public Nullable<decimal> Step05Ohms { get; set; }
        public Nullable<decimal> Step06Ohms { get; set; }
    
        public virtual PartReceived PartReceived { get; set; }
        public virtual PassFail03 PassFail03 { get; set; }
        public virtual PassFail08 PassFail08 { get; set; }
        public virtual PassFail11 PassFail11 { get; set; }
        public virtual PassFail13 PassFail13 { get; set; }
    }
}
